parameters:
#    jjbachiller_association.example.class: Jjbachiller\AssociationBundle\Example

services:
#    jjbachiller_association.example:
#        class: %jjbachiller_association.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
