jjbachiller_association:
    resource: "@JjbachillerAssociationBundle/Resources/config/routing.yml"
    prefix:   /

jjbachiller_blog:
    resource: "@JjbachillerBlogBundle/Resources/config/routing.yml"
    prefix:   /