JjbachillerBlogBundle_homepage:
    pattern: /
    defaults: { _controller: JjbachillerBlogBundle:Page:index }
    requirements:
        _method: GET

JjbachillerBlogBundle_about:
    pattern: /about
    defaults: { _controller: JjbachillerBlogBundle:Page:about }
    requirements:
        _method: GET

JjbachillerBlogBundle_contact:
    pattern: /contact
    defaults: { _controller: JjbachillerBlogBundle:Page:contact }
    requirements:
        _method: GET|POST