parameters:
#    jjbachiller_blog.example.class: Jjbachiller\BlogBundle\Example

services:
#    jjbachiller_blog.example:
#        class: %jjbachiller_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
